//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSMoTR.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSMoTR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_arrow_down {
            get {
                object obj = ResourceManager.GetObject("image_arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_arrow_left {
            get {
                object obj = ResourceManager.GetObject("image_arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_arrow_right {
            get {
                object obj = ResourceManager.GetObject("image_arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_arrow_up {
            get {
                object obj = ResourceManager.GetObject("image_arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_circle {
            get {
                object obj = ResourceManager.GetObject("image_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0 66 16
        ///0 70,5 16
        ///59 66 16
        ///59 70,5 12
        ///64 65 16
        ///64 68 12
        ///64 71,5 12
        ///103 65 8
        ///103 71,5 8
        ///106 68 8
        ///107,5 22 12
        ///107,5 60,5 8
        ///107,5 76 8
        ///107,5 114,5 16
        ///108 0 16
        ///108 17 12
        ///108 119,5 16
        ///108 136,5 16
        ///110,5 22 12
        ///110,5 63,5 8
        ///110,5 72,5 8
        ///110,5 114,5 12
        ///113 0 16
        ///113 17 16
        ///113 119,5 12
        ///113 136,5 16
        ///113,5 22 16
        ///113,5 60,5 8
        ///113,5 76 8
        ///113,5 114,5 12
        ///115 68 8
        ///118 65 8
        ///118 71,5 8
        ///130,5 65 12
        ///130,5 68 12
        ///130,5 71,5 12
        ///135,5 66 12
        ///135,5 70,5 12
        ///147,5 66 12
        ///147,5 70,5 12
        ///152,5 65 12        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string points {
            get {
                return ResourceManager.GetString("points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0 70,5 16 straight 59 70,5 12
        ///59 66 16 straight 0 66 16
        ///59 70,5 12 straight 64 71,5 12
        ///59 70,5 12 straight 64 68 12
        ///64 65 16 straight 59 66 16
        ///64 68 12 straight 106 68 8
        ///64 71,5 12 straight 103 71,5 8
        ///103 65 8 straight 64 65 16
        ///103 71,5 8 curveX 107,5 76 8
        ///103 71,5 8 straight 118 71,5 8
        ///106 68 8 curveX 113,5 60,5 8
        ///107,5 22 12 straight 107,5 60,5 8
        ///107,5 60,5 8 curveY 103 65 8
        ///107,5 60,5 8 straight 107,5 76 8
        ///107,5 76 8 straight 107,5 114,5 16
        ///107,5 114,5 16 straight 108 119,5 16
        ///108 0 16 st [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string routes {
            get {
                return ResourceManager.GetString("routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на X=100,5; Y=68; Speed=8; Type=up; GD=25; RD=25; SSC=Green; OL=40; LS=False
        ///X=100,5; Y=71,5; Speed=8; Type=usual; GD=25; RD=25; SSC=Green; OL=70; LS=False
        ///X=107,5; Y=58; Speed=0; Type=usual; GD=25; RD=25; SSC=Red; OL=55; LS=False
        ///X=110,5; Y=58; Speed=0; Type=right; GD=25; RD=25; SSC=Red; OL=40; LS=False
        ///X=110,5; Y=78; Speed=0; Type=left; GD=25; RD=25; SSC=Red; OL=40; LS=False
        ///X=113,5; Y=78; Speed=0; Type=usual; GD=25; RD=25; SSC=Red; OL=55; LS=False
        ///X=120,5; Y=65; Speed=8; Type=usual; GD=25; RD=25; SSC= [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string traffic_lights {
            get {
                return ResourceManager.GetString("traffic_lights", resourceCulture);
            }
        }
    }
}
